DBS_grid/Models/PaymentOrder.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DBS_grid.Models
{
    public class PaymentOrder
    {
        public int ID { get; set; }

        [Display(Name = "Счёт отправителя")]
        [Required]
        public string SenderAccount { get; set; }
        [Display(Name = "Счёт получателя")]
        [Required]
        public string ReceiverAccount { get; set; }
        [Display(Name = "Сумма")]
        public decimal Sum { get; set; }
        [Display(Name = "Назначение платежа")]
        [Required]
        public string Reference { get; set; }
        
        public enum OrderStatus
        {
            [Display(Name = "Обработка")]
            Processing = 1,
            [Display(Name = "Исполнен")]
            Performed = 2,
            [Display(Name = "Отказан")]
            Refused = 3,
            [Display(Name = "Не отправлен")]
            NotSent = 4
        };
        [Display(Name = "Статус")]
        public OrderStatus Status { get; set; } = OrderStatus.NotSent;
    }
}

DBS_grid/Models/PaymentOrderDTO.cs
namespace DBS_grid.Models
{
    public class PaymentOrderDTO
    {
        public int DboID { get; set; }

        public string PayerAccountNumber { get; set; }

        public string ReceiverAccountNumber { get; set; }

        public decimal Amount { get; set; }

        public string PaymentDetails { get; set; }

        public PaymentOrderDTO(PaymentOrder payment)
        {
            this.DboID = payment.ID;
            this.PayerAccountNumber = payment.SenderAccount;
            this.ReceiverAccountNumber = payment.ReceiverAccount;
            this.Amount = payment.Sum;
            this.PaymentDetails = payment.Reference;
        }
    }
}

DBS_grid/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace DBS_grid.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

DBS_grid/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace DBS_grid.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

DBS_grid/Pages/PaymentOrders/Create.cshtml.cs
using DBS_grid.Data;
using DBS_grid.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace DBS_grid.Pages.PaymentOrders
{
    public class CreateModel : PageModel
    {
        private readonly DBS_gridContext _context;

        public CreateModel(DBS_gridContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public PaymentOrder PaymentOrder { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.PaymentOrder.Add(PaymentOrder);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

DBS_grid/Pages/PaymentOrders/Details.cshtml.cs
using DBS_grid.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace DBS_grid.Pages.PaymentOrders
{
    public class DetailsModel : PageModel
    {
        private readonly DBS_grid.Data.DBS_gridContext _context;

        public DetailsModel(DBS_grid.Data.DBS_gridContext context)
        {
            _context = context;
        }

        public PaymentOrder PaymentOrder { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PaymentOrder = await _context.PaymentOrder.FirstOrDefaultAsync(m => m.ID == id);

            if (PaymentOrder == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

DBS_grid/Pages/PaymentOrders/Index.cshtml.cs
using DBS_grid.Data;
using DBS_grid.Interfaces;
using DBS_grid.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RestEase;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DBS_grid.Pages.PaymentOrders
{
    public class IndexModel : PageModel
    {
        private readonly DBS_gridContext _context;
        private readonly IPostPayment _postPayment;

        public IndexModel(DBS_gridContext context)
        {
            _context = context;
            _postPayment =
                RestClient.For<IPostPayment>("http://localhost:4545");
        }

        public IList<PaymentOrder> PaymentOrder { get; set; }

        public async Task OnGetAsync()
        {
            PaymentOrder = await _context.PaymentOrder.ToListAsync();
        }


        public async Task<IActionResult> OnPostSendAllAsync()
        {
            var paymentOrders =
                _context.PaymentOrder.Where
                (p => p.Status == Models.PaymentOrder.OrderStatus.NotSent);

            foreach (PaymentOrder po in paymentOrders)
            {
                po.Status = Models.PaymentOrder.OrderStatus.Processing;
                await _postPayment.SendPaymentAsync(new PaymentOrderDTO(po));
            }
            await _context.SaveChangesAsync();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostSendOneAsync(int id)
        {
            var paymentOrder = _context.PaymentOrder.Find(id);
            if (paymentOrder != null)
            {
                paymentOrder.Status = Models.PaymentOrder.OrderStatus.Processing;
                await _postPayment.SendPaymentAsync(new PaymentOrderDTO(paymentOrder));
            }
            await _context.SaveChangesAsync();
            return RedirectToPage();
        }
    }
}

DBS_grid/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace DBS_grid.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

DBS_grid/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DBS_grid/Pages/PaymentOrders/Create.cshtml
@page
@model DBS_grid.Pages.PaymentOrders.CreateModel

@{
    ViewData["Title"] = "Создать платёжное поручение";
}

<h1>Создать платёжное поручение</h1>

<!-- <h4>PaymentOrder</h4> -->
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PaymentOrder.SenderAccount" class="control-label"></label>
                <input asp-for="PaymentOrder.SenderAccount" class="form-control" />
                <span asp-validation-for="PaymentOrder.SenderAccount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentOrder.ReceiverAccount" class="control-label"></label>
                <input asp-for="PaymentOrder.ReceiverAccount" class="form-control" />
                <span asp-validation-for="PaymentOrder.ReceiverAccount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentOrder.Sum" class="control-label"></label>
                <input asp-for="PaymentOrder.Sum" class="form-control" />
                <span asp-validation-for="PaymentOrder.Sum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentOrder.Reference" class="control-label"></label>
                <input asp-for="PaymentOrder.Reference" class="form-control" />
                <span asp-validation-for="PaymentOrder.Reference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать и отправить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Вернуться назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DBS_grid/Pages/PaymentOrders/Details.cshtml
@page "{id:int?}"
@model DBS_grid.Pages.PaymentOrders.DetailsModel

@{
    ViewData["Title"] = "Детали";
}

<h1>Детали</h1>

<div>
    <h4>Платёжное поручение</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentOrder.SenderAccount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PaymentOrder.SenderAccount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentOrder.ReceiverAccount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PaymentOrder.ReceiverAccount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentOrder.Sum)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PaymentOrder.Sum)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentOrder.Reference)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PaymentOrder.Reference)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentOrder.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PaymentOrder.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Index">Вернуться назад</a>
</div>

DBS_grid/Pages/PaymentOrders/Index.cshtml
@page
@model DBS_grid.Pages.PaymentOrders.IndexModel

@{
    ViewData["Title"] = "Начальная страница";
}

<h1>Начало</h1>

<p>
    <a asp-page="Create">Создать новое платёжное поручение</a>
</p>
<form method="post">
    <button asp-page-handler="SendAll">
        Послать новые платёжные поручения в АБС
    </button>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PaymentOrder[0].SenderAccount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentOrder[0].ReceiverAccount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentOrder[0].Sum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentOrder[0].Reference)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentOrder[0].Status)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.PaymentOrder) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SenderAccount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReceiverAccount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reference)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-page="./Details" asp-route-id="@item.ID">Детали</a>
            </td>
            <td>
                <form method="post">
                    <button asp-page-handler="SendOne" asp-route-id="@item.ID">
                        Послать в АБС
                    </button>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>

DBS_grid/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DBS_grid</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/PaymentOrders/Index">DBS_grid</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DBS_grid
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>